# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant rsync-auto

VAGRANTFILE_API_VERSION = "2"
HOST_NAME = "docker"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

if Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.auto_update = false
end

    (1..2).each do |i|
      config.vm.define "node-#{i}" do |node|
        node.vm.box = "ubuntu/jammy64"
        node.vm.hostname = "node#{i}"
        node.vm.network "private_network", ip: "192.168.200.10#{i}"
        node.vm.provision "shell", inline: <<-SHELL
          apt-get -y -qq update
          apt-get -y -qq install python3
        SHELL
        node.vm.ignore_box_vagrantfile = true
        node.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        node.vm.provider :virtualbox do |vb|
          #vb.gui = true
          #vb.name = HOSTNAME
          vb.memory = 1048
          vb.cpus = 1
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          vb.customize ["modifyvm", :id, "--ioapic", "on"]
          vb.customize ["modifyvm", :id, "--description", "k8s worker node"]
          vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
        end
      end
    end

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/jammy64"
    #master.vm.box = "centos/8"
    #master.vm.box = "centos/stream8"
    #master.vm.box = "generic/alpine316"
    #master.vm.hostname = HOST_NAME
    master.vm.provider :virtualbox do |vb|
      #vb.gui = true
      vb.name = HOST_NAME
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--description", "docker environment"]
     end

    master.vm.network "private_network", ip: "192.168.200.200"
    master.vm.synced_folder ".", "/vagrant", type: "rsync", create: "true"
    # Rest API
    master.vm.network "forwarded_port", guest: 5000, host: 5000
    # Prometheus
    master.vm.network "forwarded_port", guest: 9090, host: 9090
    # jenkins
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.vm.network "forwarded_port", guest: 8081, host: 8081

    master.vm.provision "shell", inline: <<-SHELL
       cd /vagrant/vagrant-scripts
          chmod +x *.sh
        ls -al
        cat /etc/os-release
        #sh bootstrap-alpine.sh
        #sh bootstrap-centos.sh
        sh bootstrap-ubuntu.sh
        docker-compose -f ../apps/docker-compose.yml up --build -d
    SHELL
  end

#  master.vm.provision "ansible" do |ansible|
#    ansible.compatibility_mode = "2.0"
#    ansible.playbook = "provisioning/main.yml"
#  end

end
