FROM ubuntu



RUN mkdir -p /app && \
  apt-get -y -qq update && \
  apt-get -y -qq install python3 iputils-ping python3-pip &&\
  (useradd -m ansible -s /bin/bash || true) &&\
  python3 -m pip install --user ansible &&\
  python3 -m pip install --user ansible "ara[server]" &&\
  export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)" &&\
  export PATH=$PATH:/root/.local/bin &&\
  apt-get autoremove -y -q &&\
  apt-get clean -y -q

COPY inventory.yaml /app
WORKDIR /app