FROM rockylinux:9

USER root

RUN apt-get -y -qq update &&\
  apt-get -y -qq install openssh-server python3 iputils-ping python3-pip &&\
  useradd -m user -s /bin/bash &&\
  (echo "ansible:ansible" | chpasswd) &&\
  su - ansible -c "mkdir -p ~/.ssh" &&\
  su - ansible -c "chmod 700 ~/.ssh" &&\
  systemctl enable ssh &&\
  apt-get autoremove -y -q &&\
  apt-get clean -y -q

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
