---
- name: Install python in target node with ansible
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: install python
      raw: 'apt-get -y -qq update && apt-get -y -qq install python3'
      args:
        executable: /bin/bash
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'