---
- name: Playbook
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: ensure apache is at the latest version
      package:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: ensure apache is running
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"
